alias: Servant Call Buttons demo
description: "Determine what happens when one of the buttons is pressed "
trigger:
  - platform: state
    entity_id:
      - binary_sensor.servant_call_buttons_button_1
    to: "on"
    id: Button 1 pressed
  - platform: state
    entity_id:
      - binary_sensor.servant_call_buttons_button_2
    to: "on"
    id: Button 2 pressed
  - platform: state
    entity_id:
      - binary_sensor.servant_call_buttons_button_3
    to: "on"
    id: Button 3 pressed
  - platform: state
    entity_id:
      - binary_sensor.servant_call_buttons_button_4
    to: "on"
    id: Button 4 pressed
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id: Button 1 pressed
        sequence:
          - repeat:
              count: 2
              sequence:
                - service: light.toggle
                  data: {}
                  target:
                    entity_id: light.servant_call_buttons_on_board_led
                - delay:
                    milliseconds: 250
      - conditions:
          - condition: trigger
            id: Button 2 pressed
        sequence:
          - service: light.turn_on
            target:
              entity_id: light.servant_call_buttons_on_board_led
            data: {}
          - repeat:
              count: 4
              sequence:
                - service: light.toggle
                  data: {}
                  target:
                    entity_id: light.servant_call_buttons_on_board_led
                - delay:
                    milliseconds: 250
      - conditions:
          - condition: trigger
            id: Button 3 pressed
        sequence:
          - service: light.turn_on
            target:
              entity_id: light.servant_call_buttons_on_board_led
            data: {}
          - repeat:
              count: 6
              sequence:
                - service: light.toggle
                  data: {}
                  target:
                    entity_id: light.servant_call_buttons_on_board_led
                - delay:
                    milliseconds: 250
      - conditions:
          - condition: trigger
            id: Button 4 pressed
        sequence:
          - service: light.turn_on
            target:
              entity_id: light.servant_call_buttons_on_board_led
            data: {}
          - repeat:
              count: 8
              sequence:
                - service: light.toggle
                  data: {}
                  target:
                    entity_id: light.servant_call_buttons_on_board_led
                - delay:
                    milliseconds: 250
mode: queued
